version: "3.9"

services:
  dashboard:
    build: .
    container_name: dashboard
    ports:
      - "7860:7860"   
    volumes:
      - ./dashboard.db:/app/dashboard.db   # ถ้าอยากเก็บ DB ข้างนอก
    restart: unless-stopped